services:
  web-app:
    build:
      context: ./Web App
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./Web App:/app
      - ./Web App/logs:/app/logs
