version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards:/var/lib/grafana/dashboards
      - ./dashboards/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    restart: unless-stopped

  mongodb-exporter:
    image: percona/mongodb_exporter:0.44.0-amd64
    container_name: mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://exporter:exporterpassword@host.docker.internal:27017/admin
    command:
      - --mongodb.collect-oplatencies
      - --mongodb.collect-connections
      - --mongodb.collect-database
      - --mongodb.collect-collection
      - --mongodb.collect-index
      - --mongodb.collect-profile
      - --mongodb.collect-replset
      - --mongodb.collect-top
    ports:
      - "9216:9216"
    expose:
      - 9216
    networks:
      - monitoring
    restart: unless-stopped