{
 "title": "Task Manager Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total[1m])/16)\r\n",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sum by (device) (rate(node_cpu_seconds_total[5m])/16)",
     "legendFormat": "All CPUs"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes\r\n", "legendFormat": "Installed Memory" },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\r\n",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)\r\n",
     "legendFormat": "Swapped Memory"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Storage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (device) (node_filesystem_free_bytes/8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum (node_filesystem_free_bytes{device !~ \"none|rootfs|snapfuse\"}) by (device) / sum (node_filesystem_size_bytes{device != \"none|rootfs|snapfuse\"}) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}