FROM python:3.12-slim

WORKDIR /app

# Install required system packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sysstat \
    && rm -rf /var/lib/apt/lists/*

# Copy the exporter script
COPY metrics_exporter.py /app/

# Create logs directory
RUN mkdir -p /app/logs

# Install Python dependencies
RUN pip install --no-cache-dir prometheus_client==0.17.1

# Expose the metrics port
EXPOSE 18000

# Run the exporter
CMD ["python", "metrics_exporter.py"] 